### ISSUE TITLE
No merit of multiGPU on supMT

### ISSUE THREAD

**Issue by Dolprimates** [facebookresearch/XLM#121]
As I compared oneGPU and multiGPU, the training speed and Metrices result were completely the same(I fixed the seed of pytorch and numpy).

Then, I thought multiGPU benefit on the memory use, but as I increased the beamsize from 1 to 4, only multiGPU was out of memory(the error is below).

-- = my XLM path
--- = my pyenv path
```
INFO - 07/08/19 17:46:32 - 1:22:22 - ============ End of epoch 0 ============
INFO - 07/08/19 17:46:32 - 1:22:22 -    6250 -   34.75 sent/s -  1396.93 words/s - MT-zh-ja:  2.6070 - Transformer LR = 8.0000e-05
INFO - 07/08/19 17:46:32 - 1:22:22 - ============ End of epoch 0 ============
INFO - 07/08/19 17:47:02 - 1:22:53 - epoch -> 0.000000
INFO - 07/08/19 17:47:02 - 1:22:53 - valid_zh-ja_mt_ppl -> 13.868680
INFO - 07/08/19 17:47:02 - 1:22:53 - valid_zh-ja_mt_acc -> 56.600500
INFO - 07/08/19 17:47:02 - 1:22:53 - test_zh-ja_mt_ppl -> 13.772691
INFO - 07/08/19 17:47:02 - 1:22:53 - test_zh-ja_mt_acc -> 56.804556
INFO - 07/08/19 17:47:02 - 1:22:53 - ============ Starting epoch 1 ... ============
Traceback (most recent call last):
  File "train.py", line 330, in <module>
    main(params)
  File "train.py", line 305, in main
    scores = evaluator.run_all_evals(trainer)
  File "--/src/evaluation/evaluator.py", line 181, in run_all_evals
    self.evaluate_mt(scores, data_set, lang1, lang2, eval_bleu)
  File "--/src/evaluation/evaluator.py", line 392, in evaluate_mt
    max_len=max_len
  File "--/src/model/transformer.py", line 588, in generate_beam
    cache=cache
  File "--/src/model/transformer.py", line 323, in forward
    return self.fwd(**kwargs)
  File "--/src/model/transformer.py", line 392, in fwd
    attn = self.attentions[i](tensor, attn_mask, cache=cache)
  File "---/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "--/src/model/transformer.py", line 209, in forward
    scores = torch.matmul(q, k.transpose(2, 3))                           # (bs, n_heads, qlen, klen)
RuntimeError: CUDA out of memory. Tried to allocate 138.00 MiB (GPU 0; 11.93 GiB total capacity; 10.40 GiB already allocated; 31.44 MiB free; 993.83 MiB cached)
```

So, I don't see any merit of multiGPU now.
What is the difference of using oneGPU and multiGPU?

**Comment by glample** [comment]
The number of words per second is printed per GPU, so if you have 8 GPU and that each process prints 1000 words/s, it means you are actually training at 8000 words/s. If you see the same speed metric with 1 and 8 GPU it is a good sign, as it means that the training speed is linear with the number of GPUs (although it's often a bit sub-linear).

**Comment by Dolprimates** [comment]
I don't mean "speed metrics".
As I start training oneGPU and multiGPU simultaneously, each epoch ends at the same time, and Metrics(BLUE, etc..) are the same.
So, no speedup and no result improvement.

**Comment by glample** [comment]
It is normal that each epoch ends at the same time. An epoch with 8 GPU will have 8x more data than an epoch with 1 GPU (the notion of epoch is strict to a single process, unlike the way it is done in imagenet typically). So at the end of one epoch, the 1-GPU model will be trained on 8x less data than the 8-GPU model , so the 8-GPU model should have a better performance.

If the performance is not better, can you check that each process outputs the exact same metrics? Like, that for each process `valid_zh-ja_mt_ppl` and `valid_zh-ja_mt_acc` have the exact same values? If not, it means that the model is not synchronized properly across process, but this not expected and I don't think this is the issue.

If the model is properly synchronized and does not get a better performance with 8 GPUs, it could be that either because you have not trained it long enough to see a difference (but I would find this surprising, difference should be visible after 1 epoch), or that the training set is too small and there is little interest in using multiple GPUs. Can you check that the training loss is also the same with 1 and 8 GPUs? If the training set is small, having more GPUs will not be very useful on the validation set, but should overfit more on the training set.

**Comment by Dolprimates** [comment]
Solved the issue.

The cause was the seed fix. like below

at
https://github.com/facebookresearch/XLM/blob/53449a057db337614d17c589d523de5803f8fa93/src/model/transformer.py#L246

added
```
        torch.cuda.manual_seed(0)
        torch.cuda.manual_seed_all(0)

        torch.backends.cudnn.enabled = False
        torch.backends.cudnn.benchmark = False
        torch.backends.cudnn.deterministic = True
        np.random.seed(0)
```

So, each GPU seemed to produce completely the same weight at each node of transformer.
It was really interesting that this result in no performance improvement.

**Comment by glample** [comment]
The distributed process will synchronize the parameters before the training start. Then, the gradients are shared at each update, so the parameters will remain synchronized forever, and you should not need to do anything. You don't need to set any seed of CUDNN special configuration.

**Comment by Dolprimates** [comment]
Can we make multiGPU process reproducible?
I fixed the seed for it and made oneGPU process reproducible.

https://pytorch.org/docs/stable/notes/randomness.html

**Comment by glample** [comment]
Actually I wonder if one of the reasons why you didn't observe an improvement with multi-GPU is that since you set a same seed on all GPUs, each process was training on the same batch (all processes are iterating over the dataset in the same order). In that setting, all gradients will be identical and averaging them will give the same performance as if you were to use a single GPU.

If fixing the seed on 1 GPU makes the process reproducible, then it will also be reproducible on multiple GPUs. But you will need to be sure that you are not iterating with the same batches on several GPUs (by setting the seed to `seed + params.local_rank` and not just `seed`, for instance).
