### ISSUE TITLE
CUDA out of memory: unsupervised MT with pretrained model

### ISSUE THREAD

**Issue by Akella17** [facebookresearch/XLM#197]
@glample @aconneau I am running out of memory while trying to run unsupervised MT experiment with the pretrained model mlm_enfr_1024.pth even for batch size = 1 on a 12GB GPU. The same problem persisted even when I tried running this on 2 GPUs. However, when I reduce the emb_size from 1024 to 512 and get rid of the pretrained model, everything seems to work (even for a batch size of 32). Can you explain why I might be facing this issue? Is there no way I can use the pretrained model?
```
python train.py --batch_size 1 --fp16 True --amp 1 --exp_name unsupMT_enfr --dump_path ./dumped/ --reload_model 'mlm_enfr_1024.pth,mlm_enfr_1024.pth' --data_path ./data/processed/en-fr/ --lgs 'en-fr' --ae_steps 'en,fr' --bt_steps 'en-fr-en,fr-en-fr' --word_shuffle 3 --word_dropout 0.1 --word_blank 0.1 --lambda_ae '0:1,100000:0.1,300000:0' --encoder_only false --emb_dim 1024 --n_layers 6 --n_heads 8 --dropout 0.1 --attention_dropout 0.1 --gelu_activation true --tokens_per_batch 2000 --bptt 256 --optimizer adam_inverse_sqrt,beta1=0.9,beta2=0.98,lr=0.0001 --epoch_size 200000 --eval_bleu true --stopping_criterion 'valid_en-fr_mt_bleu,10' --validation_metrics 'valid_en-fr_mt_bleu'
```

```
FAISS library was not found.
FAISS not available. Switching to standard nearest neighbors search implementation.
SLURM job: False
0 - Number of nodes: 1
0 - Node ID        : 0
0 - Local rank     : 0
0 - Global rank    : 0
0 - World size     : 1
0 - GPUs per node  : 1
0 - Master         : True
0 - Multi-node     : False
0 - Multi-GPU      : False
0 - Hostname       : nlp-server
INFO - 09/14/19 00:28:47 - 0:00:00 - ============ Initialized logger ============
INFO - 09/14/19 00:28:47 - 0:00:00 - accumulate_gradients: 1
                                     ae_steps: ['en', 'fr']
                                     amp: 1
                                     asm: False
                                     attention_dropout: 0.1
                                     batch_size: 1
                                     beam_size: 1
                                     bptt: 256
                                     bt_src_langs: ['en', 'fr']
                                     bt_steps: [('en', 'fr', 'en'), ('fr', 'en', 'fr')]
                                     clip_grad_norm: 5
                                     clm_steps: []
                                     command: python train.py --batch_size 1 --fp16 True --amp 1 --exp_name unsupMT_enfr --dump_path './dumped/' --reload_model 'mlm_enfr_1024.pth,mlm_enfr_1024.pth' --data_path './data/processed/en-fr/' --lgs 'en-fr' --ae_steps 'en,fr' --bt_steps 'en-fr-en,fr-en-fr' --word_shuffle 3 --word_dropout '0.1' --word_blank '0.1' --lambda_ae '0:1,100000:0.1,300000:0' --encoder_only false --emb_dim 1024 --n_layers 6 --n_heads 8 --dropout '0.1' --attention_dropout '0.1' --gelu_activation true --tokens_per_batch 2000 --bptt 256 --optimizer 'adam_inverse_sqrt,beta1=0.9,beta2=0.98,lr=0.0001' --epoch_size 200000 --eval_bleu true --stopping_criterion 'valid_en-fr_mt_bleu,10' --validation_metrics 'valid_en-fr_mt_bleu' --exp_id "zm5ierxx20"
                                     context_size: 0
                                     data_path: ./data/processed/en-fr/
                                     debug: False
                                     debug_slurm: False
                                     debug_train: False
                                     dropout: 0.1
                                     dump_path: ./dumped/unsupMT_enfr/zm5ierxx20
                                     early_stopping: False
                                     emb_dim: 1024
                                     encoder_only: False
                                     epoch_size: 200000
                                     eval_bleu: True
                                     eval_only: False
                                     exp_id: zm5ierxx20
                                     exp_name: unsupMT_enfr
                                     fp16: True
                                     gelu_activation: True
                                     global_rank: 0
                                     group_by_size: True
                                     id2lang: {0: 'en', 1: 'fr'}
                                     is_master: True
                                     is_slurm_job: False
                                     lambda_ae: 0:1,100000:0.1,300000:0
                                     lambda_bt: 1
                                     lambda_clm: 1
                                     lambda_mlm: 1
                                     lambda_mt: 1
                                     lambda_pc: 1
                                     lang2id: {'en': 0, 'fr': 1}
                                     langs: ['en', 'fr']
                                     length_penalty: 1
                                     lg_sampling_factor: -1
                                     lgs: en-fr
                                     local_rank: 0
                                     master_port: -1
                                     max_batch_size: 0
                                     max_epoch: 100000
                                     max_len: 100
                                     max_vocab: -1
                                     min_count: 0
                                     mlm_steps: []
                                     mono_dataset: {'en': {'train': './data/processed/en-fr/train.en.pth', 'valid': './data/processed/en-fr/valid.en.pth', 'test': './data/processed/en-fr/test.en.pth'}, 'fr': {'train': './data/processed/en-fr/train.fr.pth', 'valid': './data/processed/en-fr/valid.fr.pth', 'test': './data/processed/en-fr/test.fr.pth'}}
                                     mt_steps: []
                                     multi_gpu: False
                                     multi_node: False
                                     n_gpu_per_node: 1
                                     n_heads: 8
                                     n_langs: 2
                                     n_layers: 6
                                     n_nodes: 1
                                     node_id: 0
                                     optimizer: adam_inverse_sqrt,beta1=0.9,beta2=0.98,lr=0.0001
                                     para_dataset: {('en', 'fr'): {'valid': ('./data/processed/en-fr/valid.en-fr.en.pth', './data/processed/en-fr/valid.en-fr.fr.pth'), 'test': ('./data/processed/en-fr/test.en-fr.en.pth', './data/processed/en-fr/test.en-fr.fr.pth')}}
                                     pc_steps: []
                                     reload_checkpoint: 
                                     reload_emb: 
                                     reload_model: mlm_enfr_1024.pth,mlm_enfr_1024.pth
                                     sample_alpha: 0
                                     save_periodic: 0
                                     share_inout_emb: True
                                     sinusoidal_embeddings: False
                                     split_data: False
                                     stopping_criterion: valid_en-fr_mt_bleu,10
                                     tokens_per_batch: 2000
                                     use_lang_emb: True
                                     use_memory: False
                                     validation_metrics: valid_en-fr_mt_bleu
                                     word_blank: 0.1
                                     word_dropout: 0.1
                                     word_keep: 0.1
                                     word_mask: 0.8
                                     word_mask_keep_rand: 0.8,0.1,0.1
                                     word_pred: 0.15
                                     word_rand: 0.1
                                     word_shuffle: 3.0
                                     world_size: 1
INFO - 09/14/19 00:28:47 - 0:00:00 - The experiment will be stored in ./dumped/unsupMT_enfr/zm5ierxx20
                                     
INFO - 09/14/19 00:28:47 - 0:00:00 - Running command: python train.py --batch_size 1 --fp16 True --amp 1 --exp_name unsupMT_enfr --dump_path './dumped/' --reload_model 'mlm_enfr_1024.pth,mlm_enfr_1024.pth' --data_path './data/processed/en-fr/' --lgs 'en-fr' --ae_steps 'en,fr' --bt_steps 'en-fr-en,fr-en-fr' --word_shuffle 3 --word_dropout '0.1' --word_blank '0.1' --lambda_ae '0:1,100000:0.1,300000:0' --encoder_only false --emb_dim 1024 --n_layers 6 --n_heads 8 --dropout '0.1' --attention_dropout '0.1' --gelu_activation true --tokens_per_batch 2000 --bptt 256 --optimizer 'adam_inverse_sqrt,beta1=0.9,beta2=0.98,lr=0.0001' --epoch_size 200000 --eval_bleu true --stopping_criterion 'valid_en-fr_mt_bleu,10' --validation_metrics 'valid_en-fr_mt_bleu'

WARNING - 09/14/19 00:28:47 - 0:00:00 - Signal handler installed.
INFO - 09/14/19 00:28:47 - 0:00:00 - ============ Monolingual data (en)
INFO - 09/14/19 00:28:47 - 0:00:00 - Loading data from ./data/processed/en-fr/train.en.pth ...
INFO - 09/14/19 00:28:50 - 0:00:03 - 97888424 words (64139 unique) in 3782548 sentences. 0 unknown words (0 unique) covering 0.00% of the data.
INFO - 09/14/19 00:28:54 - 0:00:07 - Removed 0 empty sentences.
INFO - 09/14/19 00:28:54 - 0:00:07 - Removed 10416 too long sentences.

INFO - 09/14/19 00:28:54 - 0:00:07 - Loading data from ./data/processed/en-fr/valid.en.pth ...
INFO - 09/14/19 00:28:54 - 0:00:08 - 69727 words (64139 unique) in 3000 sentences. 1 unknown words (1 unique) covering 0.00% of the data.

INFO - 09/14/19 00:28:55 - 0:00:08 - Loading data from ./data/processed/en-fr/test.en.pth ...
INFO - 09/14/19 00:28:55 - 0:00:08 - 76086 words (64139 unique) in 3003 sentences. 0 unknown words (0 unique) covering 0.00% of the data.

INFO - 09/14/19 00:28:55 - 0:00:08 - ============ Monolingual data (fr)
INFO - 09/14/19 00:28:55 - 0:00:08 - Loading data from ./data/processed/en-fr/train.fr.pth ...
INFO - 09/14/19 00:28:58 - 0:00:11 - 126525882 words (64139 unique) in 4837799 sentences. 0 unknown words (0 unique) covering 0.00% of the data.
INFO - 09/14/19 00:29:04 - 0:00:17 - Removed 0 empty sentences.
INFO - 09/14/19 00:29:05 - 0:00:18 - Removed 16598 too long sentences.

INFO - 09/14/19 00:29:05 - 0:00:18 - Loading data from ./data/processed/en-fr/valid.fr.pth ...
INFO - 09/14/19 00:29:05 - 0:00:18 - 79577 words (64139 unique) in 3000 sentences. 1 unknown words (1 unique) covering 0.00% of the data.

INFO - 09/14/19 00:29:05 - 0:00:18 - Loading data from ./data/processed/en-fr/test.fr.pth ...
INFO - 09/14/19 00:29:05 - 0:00:18 - 86345 words (64139 unique) in 3003 sentences. 0 unknown words (0 unique) covering 0.00% of the data.


INFO - 09/14/19 00:29:05 - 0:00:18 - ============ Parallel data (en-fr)
INFO - 09/14/19 00:29:05 - 0:00:18 - Loading data from ./data/processed/en-fr/valid.en-fr.en.pth ...
INFO - 09/14/19 00:29:05 - 0:00:18 - 69727 words (64139 unique) in 3000 sentences. 1 unknown words (1 unique) covering 0.00% of the data.
INFO - 09/14/19 00:29:05 - 0:00:18 - Loading data from ./data/processed/en-fr/valid.en-fr.fr.pth ...
INFO - 09/14/19 00:29:05 - 0:00:18 - 79577 words (64139 unique) in 3000 sentences. 1 unknown words (1 unique) covering 0.00% of the data.
INFO - 09/14/19 00:29:06 - 0:00:19 - Removed 0 empty sentences.

INFO - 09/14/19 00:29:06 - 0:00:19 - Loading data from ./data/processed/en-fr/test.en-fr.en.pth ...
INFO - 09/14/19 00:29:06 - 0:00:19 - 76086 words (64139 unique) in 3003 sentences. 0 unknown words (0 unique) covering 0.00% of the data.
INFO - 09/14/19 00:29:06 - 0:00:19 - Loading data from ./data/processed/en-fr/test.en-fr.fr.pth ...
INFO - 09/14/19 00:29:06 - 0:00:19 - 86345 words (64139 unique) in 3003 sentences. 0 unknown words (0 unique) covering 0.00% of the data.
INFO - 09/14/19 00:29:06 - 0:00:19 - Removed 0 empty sentences.


INFO - 09/14/19 00:29:06 - 0:00:19 - ============ Data summary
INFO - 09/14/19 00:29:06 - 0:00:19 - Monolingual data   - train -           en:   3782548
INFO - 09/14/19 00:29:06 - 0:00:19 - Monolingual data   - valid -           en:      3000
INFO - 09/14/19 00:29:06 - 0:00:19 - Monolingual data   -  test -           en:      3003
INFO - 09/14/19 00:29:06 - 0:00:19 - Monolingual data   - train -           fr:   4837799
INFO - 09/14/19 00:29:06 - 0:00:19 - Monolingual data   - valid -           fr:      3000
INFO - 09/14/19 00:29:06 - 0:00:19 - Monolingual data   -  test -           fr:      3003
INFO - 09/14/19 00:29:06 - 0:00:19 - Parallel data      - valid -        en-fr:      3000
INFO - 09/14/19 00:29:06 - 0:00:19 - Parallel data      -  test -        en-fr:      3003

INFO - 09/14/19 00:29:20 - 0:00:33 - Reloading encoder from mlm_enfr_1024.pth ...
INFO - 09/14/19 00:29:30 - 0:00:43 - Reloading decoder from mlm_enfr_1024.pth ...
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter layer_norm15.0.weight not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter layer_norm15.0.bias not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.0.q_lin.weight not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.0.q_lin.bias not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.0.k_lin.weight not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.0.k_lin.bias not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.0.v_lin.weight not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.0.v_lin.bias not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.0.out_lin.weight not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.0.out_lin.bias not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter layer_norm15.1.weight not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter layer_norm15.1.bias not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.1.q_lin.weight not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.1.q_lin.bias not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.1.k_lin.weight not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.1.k_lin.bias not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.1.v_lin.weight not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.1.v_lin.bias not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.1.out_lin.weight not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.1.out_lin.bias not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter layer_norm15.2.weight not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter layer_norm15.2.bias not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.2.q_lin.weight not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.2.q_lin.bias not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.2.k_lin.weight not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.2.k_lin.bias not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.2.v_lin.weight not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.2.v_lin.bias not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.2.out_lin.weight not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.2.out_lin.bias not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter layer_norm15.3.weight not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter layer_norm15.3.bias not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.3.q_lin.weight not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.3.q_lin.bias not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.3.k_lin.weight not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.3.k_lin.bias not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.3.v_lin.weight not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.3.v_lin.bias not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.3.out_lin.weight not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.3.out_lin.bias not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter layer_norm15.4.weight not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter layer_norm15.4.bias not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.4.q_lin.weight not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.4.q_lin.bias not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.4.k_lin.weight not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.4.k_lin.bias not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.4.v_lin.weight not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.4.v_lin.bias not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.4.out_lin.weight not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.4.out_lin.bias not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter layer_norm15.5.weight not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter layer_norm15.5.bias not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.5.q_lin.weight not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.5.q_lin.bias not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.5.k_lin.weight not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.5.k_lin.bias not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.5.v_lin.weight not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.5.v_lin.bias not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.5.out_lin.weight not found.
WARNING - 09/14/19 00:29:33 - 0:00:46 - Parameter encoder_attn.5.out_lin.bias not found.
INFO - 09/14/19 00:29:33 - 0:00:46 - Number of parameters (encoder): 141848203
INFO - 09/14/19 00:29:33 - 0:00:46 - Number of parameters (decoder): 167050891
INFO - 09/14/19 00:29:33 - 0:00:47 - Found 0 memories.
INFO - 09/14/19 00:29:33 - 0:00:47 - Found 12 FFN.
INFO - 09/14/19 00:29:33 - 0:00:47 - Found 264 parameters in model.
INFO - 09/14/19 00:29:34 - 0:00:47 - Optimizers: model
Selected optimization level O1:  Insert automatic casts around Pytorch functions and Tensor methods.

Defaults for this optimization level are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
INFO - 09/14/19 00:29:37 - 0:00:50 - ============ Starting epoch 0 ... ============
INFO - 09/14/19 00:29:37 - 0:00:50 - Creating new training data iterator (ae,en) ...
Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 32768.0
INFO - 09/14/19 00:29:42 - 0:00:55 - Creating new training data iterator (ae,fr) ...
Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 16384.0
INFO - 09/14/19 00:29:47 - 0:01:00 - Creating new training data iterator (bt,en) ...
Traceback (most recent call last):
  File "train.py", line 327, in <module>
    main(params)
  File "train.py", line 288, in main
    trainer.bt_step(lang1, lang2, lang3, params.lambda_bt)
  File "/home1/sukanta/Ravitej/UnsupervisedXLM/src/trainer.py", line 929, in bt_step
    self.optimize(loss)
  File "/home1/sukanta/Ravitej/UnsupervisedXLM/src/trainer.py", line 227, in optimize
    scaled_loss.backward()
  File "/home1/sukanta/anaconda3/envs/UNMT/lib/python3.6/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home1/sukanta/anaconda3/envs/UNMT/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA out of memory. Tried to allocate 470.75 MiB (GPU 0; 10.91 GiB total capacity; 9.48 GiB already allocated; 437.44 MiB free; 404.61 MiB cached)
```

**Comment by glample** [comment]
`tokens_per_batch` is the parameter that matters here. If it is set to 2000 it means the dataloader will try to fit 2000 tokens in each batch, i.e. 10 sentences of size 200, or 40 sentences of size 50, etc. If `tokens_per_batch` is set, then `batch_size` is ignored in machine translation.

`batch_size` and `bptt` will still be used for the CLM and MLM steps though, but if you just do unsupervised MT, then you should try to reduce 2000. It is already a small value though, and the number of tokens per batch has a huge impact in unsupervised MT. You can try to set it to 1000, but then I would suggest using `--amp 2 --accumulate_gradients 4` to simulate 4x larger batches (AMP O2 uses less GPU memory than AMP O1).

**Comment by Akella17** [comment]
@glample @aconneau Thanks for the help! Lowering tokens_per_batch to 1000 did the trick. Also, I am using GeForce GTX 1080 Ti GPUs which does not have tensor cores and as a result, the speedup or memory savings are not that significant with fp16. I have two GPUs available, but increasing the tokens_per_batch results in OOM instead of sharing the burden across both the GPUs. Any thoughts on why this might be the case?

**Comment by glample** [comment]
`tokens_per_batch` is a value per GPU. So if 2000 does not fit in 1 GPU it will not fit on 2. If you have `tokens_per_batch=1000` and 2 GPUs then the actual `tokens_per_batch` will be 2000.

**Comment by Akella17** [comment]
Oh right! Thank you @glample

**Comment by gunnxx** [comment]
I come across similar issue
`RuntimeError: CUDA out of memory. Tried to allocate 490.00 MiB (GPU 0; 14.73 GiB total capacity; 13.78 GiB already allocated; 77.88 MiB free; 202.38 MiB cached)`

In my case, changing `tokens_per_batch` does not affect memory. From `2000` to `50`, the error is still the same with the same details.

My command
```
python train.py \
    --exp_name baseline_id_en_unmt \
    --dump_path ./exp/baseline_id_en_unmt \
    --reload_model './pretrained/mlm_100_1280.pth,./pretrained/mlm_100_1280.pth' \
    --data_path ./data/processed/id-en-test \
    --lgs 'en-id' \
    --ae_steps 'en,id' \
    --bt_steps 'en-id-en,id-en-id' \
    --word_shuffle 3 \
    --word_dropout 0.1 \
    --word_blank 0.1 \
    --encoder_only false \
    --max_vocab 200000 \
    --emb_dim 1280 \
    --n_layers 6 \
    --n_heads 8 \
    --dropout 0.1 \
    --attention_dropout 0.1 \
    --gelu_activation true \
    --tokens_per_batch 50 \
    --accumulate_gradients 2 \
    --fp16 true \
    --amp 2 \
    --optimizer adam_inverse_sqrt,beta1=0.9,beta2=0.98,lr=0.0001 \
    --epoch_size 200000 \
    --eval_bleu true \
    --stopping_criterion 'valid_en-id_mt_bleu,10' \
    --validation_metrics 'valid_en-id_mt_bleu'
```

**Comment by PootieT** [comment]
@gunnxx I am seeing the same issue as you trying to finetune XLM-R pretrained model on 16GB GPU. `n_heads` and `n_layers` both should be 16. Still I am able to load model with `amp` 1 but during MT step it hits the OOM error (even with `tokens_per_batch`  = 20. Have you gotten passed it?

**Comment by gunnxx** [comment]
@PootieT I am sorry I already forgot about it. I also can't check what my configuration was since it was my internship work and all of the configurations are on the office's PC. If I am not mistaken, I just used smaller model or bigger GPU lmao.
