### ISSUE TITLE
RuntimeError: CUDA out of memory. Tried to allocate 498.50 MiB (GPU 0; 7.92 GiB total capacity; 6.74 GiB already allocated; 307.56 MiB free; 3.53 MiB cached)

### ISSUE THREAD

**Issue by Julisa-test** [facebookresearch/XLM#20]
Hi，@glample

I pretrained a model with the MLM objective for Mongolian and Chinese, but when I used the pretrained model for mn-zh Machine Translation, the error came. I tried reducing --batch_size from default 32 to 16, 8, 4, 2, and 1, but that didn't help. Could you have any good solutions for this to share？

The pretrained result is：
INFO - 02/28/19 09:47:19 - 1 day, 1:01:20 - ============ End of epoch 7 ============
INFO - 02/28/19 09:47:30 - 1 day, 1:01:31 - epoch -> 7.000000
INFO - 02/28/19 09:47:30 - 1 day, 1:01:31 - valid_mn_mlm_ppl -> 20.055305
INFO - 02/28/19 09:47:30 - 1 day, 1:01:31 - valid_mn_mlm_acc -> 56.151420
INFO - 02/28/19 09:47:30 - 1 day, 1:01:31 - valid_zh_mlm_ppl -> 1813.456839
INFO - 02/28/19 09:47:30 - 1 day, 1:01:31 - valid_zh_mlm_acc -> 28.312303
INFO - 02/28/19 09:47:30 - 1 day, 1:01:31 - valid_mlm_ppl -> 916.756072
INFO - 02/28/19 09:47:30 - 1 day, 1:01:31 - valid_mlm_acc -> 42.231861
INFO - 02/28/19 09:47:30 - 1 day, 1:01:31 - test_mn_mlm_ppl -> 8.259349
INFO - 02/28/19 09:47:30 - 1 day, 1:01:31 - test_mn_mlm_acc -> 65.375485
INFO - 02/28/19 09:47:30 - 1 day, 1:01:31 - test_zh_mlm_ppl -> 11569.002599
INFO - 02/28/19 09:47:30 - 1 day, 1:01:31 - test_zh_mlm_acc -> 15.452244
INFO - 02/28/19 09:47:30 - 1 day, 1:01:31 - test_mlm_ppl -> 5788.630974
INFO - 02/28/19 09:47:30 - 1 day, 1:01:31 - test_mlm_acc -> 40.413864

Train on unsupervised MT from the pretrained model
python train.py --exp_name unsupMT_mnzh --dump_path ./dumped/ --reload_model 'best-valid_mlm_ppl.pth,best-valid_mlm_ppl.pth' --data_path ./data/processed/mn-zh/ --lgs 'mn-zh' --ae_steps 'mn,zh' --bt_steps 'mn-zh-mn,zh-mn-zh' --word_shuffle 3 --word_dropout 0.1 --word_blank 0.1 --lambda_ae '0:1,100000:0.1,300000:0' --encoder_only false --emb_dim 1024 --n_layers 6 --n_heads 8 --dropout 0.1 --attention_dropout 0.1 --gelu_activation true --tokens_per_batch 2000 --batch_size 16 --bptt 256 --optimizer adam_inverse_sqrt,beta1=0.9,beta2=0.999,lr=0.0001 --epoch_size 300000 --eval_bleu true --stopping_criterion 'valid_mn-zh_mt_bleu,10' --validation_metrics 'valid_mn-zh_mt_bleu'

**Comment by glample** [comment]
The pretrained result looks good. Regarding the unsupervised MT on the pretrained model, I'm not sure why it OOM. Can you try to set `--bt_steps '' ` to temporarily disable back-translation? Just to had an idea of where the issue comes from.
Also, can you try to set `--max_batch_size 64` ? It will avoid the model to generate huge batches with a lot of very small sentences of `--tokens_per_batch` words. 

Last thing: we use this for back-translation: https://github.com/facebookresearch/XLM/blob/master/src/trainer.py#L816 it indicates that the generated back-translation should not exceed 1.3 times the length of the source sentence. It is usually true for English-French, but if in Mn-Zh sentences can be twice longer, you should replace the 1.3 by 2 (but it will be more likely to OOM as well, since generated sequences will be longer).

**Comment by Julisa-test** [comment]
Hi，@glample

Thanks for your reply！

I tried to reduce --tokens_per_batch from 2000 to 400 and it started running, but at the end of the epoch 0 when computed the BLEU and the issue reappeared. 
Also I tried set --max_batch_size 64, but that didn't help.
In addition, I tried set --bt_steps '' , there is another issue appeared.

(xlm) julisa@julisa:~/XLM/XLM$ python train.py --exp_name unsupMT_mnzh --dump_path './dumped/' --reload_model 'best-valid_mlm_ppl.pth,best-valid_mlm_ppl.pth' --data_path './data/processed/mn-zh/' --lgs 'mn-zh' --ae_steps 'mn,zh' --bt_steps '' --word_shuffle 3 --word_dropout '0.1' --word_blank '0.1' --lambda_ae '0:1,100000:0.1,300000:0' --encoder_only false --emb_dim 1024 --n_layers 6 --n_heads 8 --dropout '0.1' --attention_dropout 0 --gelu_activation true --tokens_per_batch 2000 --max_batch_size 64 --bptt 256 --optimizer 'adam_inverse_sqrt,beta1=0.9,beta2=0.98,lr=0.0001' --epoch_size 300000 --eval_bleu true --stopping_criterion 'valid_mn-zh_mt_bleu,10' --validation_metrics 'valid_mn-zh_mt_bleu'
Traceback (most recent call last):
  File "train.py", line 318, in <module>
    check_data_params(params)
  File "/home/julisa/XLM/XLM/src/data/loader.py", line 306, in check_data_params
    assert params.eval_bleu is False or len(params.mt_steps + params.bt_steps) > 0
AssertionError

**Comment by Julisa-test** [comment]
Hi，@glample

I tried set --bt_steps '' ，but it still OOM.

python train.py --exp_name unsupMT_mnzh --dump_path ./dumped/ --exp_id '19031015' --reload_model './dumped/my_mnzh_mlm/190228/best-valid_mlm_ppl.pth,./dumped/my_mnzh_mlm/190228/best-valid_mlm_ppl.pth' --data_path ./data/processed/mn-zh/ --lgs 'mn-zh' --ae_steps 'mn,zh' --bt_steps '' --word_shuffle 3 --word_dropout 0.1 --word_blank 0.1 --lambda_ae '0:1,100000:0.1,300000:0' --encoder_only false --emb_dim 1024 --n_layers 6 --n_heads 8 --dropout 0.1 --attention_dropout 0 --gelu_activation true --tokens_per_batch 400 --batch_size 16 --max_batch_size 64 --bptt 256 --optimizer adam_inverse_sqrt,beta1=0.9,beta2=0.98,lr=0.0001 --epoch_size 300000 --eval_bleu true --stopping_criterion 'valid_mn-zh_mt_bleu,10' --validation_metrics 'valid_mn-zh_mt_bleu'

INFO - 03/10/19 15:43:47 - 0:00:27 - ============ Starting epoch 0 ... ============
INFO - 03/10/19 15:43:47 - 0:00:27 - Creating new training data iterator (ae,mn) ...
/home/julisa/.pyenv/versions/xlm/lib/python3.6/site-packages/torch/nn/_reduction.py:16: UserWarning: reduction='elementwise_mean' is deprecated, please use reduction='mean' instead.
  warnings.warn("reduction='elementwise_mean' is deprecated, please use reduction='mean' instead.")
INFO - 03/10/19 15:43:48 - 0:00:28 - Creating new training data iterator (ae,zh) ...
Traceback (most recent call last):
  File "train.py", line 328, in <module>
    main(params)
  File "train.py", line 288, in main
    trainer.mt_step(lang, lang, params.lambda_ae)
  File "/home/julisa/XLM/XLM/src/trainer.py", line 769, in mt_step
    self.optimize(loss, ['encoder', 'decoder'])
  File "/home/julisa/XLM/XLM/src/trainer.py", line 130, in optimize
    loss.backward()
  File "/home/julisa/.pyenv/versions/xlm/lib/python3.6/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/julisa/.pyenv/versions/xlm/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA out of memory. Tried to allocate 98.00 MiB (GPU 0; 7.92 GiB total capacity; 5.83 GiB already allocated; 79.62 MiB free; 27.70 MiB cached)

**Comment by glample** [comment]
This is not normal, with 400 tokens per batch you should not have any issues. What GPU do you use, and what is its total capacity? From the log I can see `GPU 0; 7.92 GiB total capacity` but this seems strange to me.

**Comment by Julisa-test** [comment]
The GPU I used is NVIDIA 1070.

**Comment by Julisa-test** [comment]
Hi, @glample

I think I found a solution. I just tried reducing --emb_dim from 1024 to 512 and It works.

Thanks for everything!

**Comment by dhekrasaeed** [comment]
> 
> 
> Hi, @glample
> 
> I think I found a solution. I just tried reducing --emb_dim from 1024 to 512 and It works.
> 
> Thanks for everything!

Could share ur solution

**Comment by Panshangka** [comment]
Hello, can you share me with some information about how to translate English to Chinese as your work is about Mongolian to Chinese which is also not listed as example in this repo. My puzzle is how to preprocess the data and apply the pretrained model. Thanks in advance!

**Comment by 645709712** [comment]
@Julisa-test hi,I have a question to ask you,If you change the emb_dim, I think there will be a mismatch in the size of the variable, because the dimension of the model you trained is 1024. You force the dimension down. Is n’t there a problem?I also encountered the problem of insufficient GPU space. I am looking for a solution. I saw your reply. I just want to know the details of the solution.Thank you very much
